### ISSUE TITLE
大佬,这个我运行不起来,能指导一下吗?

### ISSUE THREAD

**Issue by cathylogs** [telanflow/TryScan#1]
大佬,这个我运行不起来,能指导一下吗?
![image](https://user-images.githubusercontent.com/39398991/134757865-94e14a4a-f00b-47f4-8783-b6fa52c0b27c.png)

**Comment by telanflow** [comment]
需要先启动sqlmap提供的API服务，然后修改配置文件，在然后启动项目

sqlmap 是一个开源项目：https://github.com/sqlmapproject/sqlmap

TryScan其实是一个壳，核心是借助sqlmap提供的api服务进行SQL注入扫描
